#!/usr/bin/env python3
"""GPNAE activation regression: generate stimulus and golden values, run the RTL under Verilator, score every element.

Writes testbenches/stimulus/<act>_{in,exp}.mem and testbenches/gpnae_test_config.svh, then runs `make verilator`.
Report lands in testbenches/results/gpnae_report.log. Use ./run_regression.sh, which sets the toolchain up first.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import time
from datetime import datetime

import numpy as np

from gpnae_tests import (ACTIVATIONS, MAX_SIGNALS, TESTS, get_test, golden,
                         write_coeff_rom, write_mem)
from number_formats import FORMATS, get_format, suggested_rel_tol

ROOT = os.path.dirname(os.path.abspath(__file__))
TB_DIR = os.path.join(ROOT, "testbenches")
STIM_DIR = os.path.join(TB_DIR, "stimulus")
RESULTS_DIR = os.path.join(TB_DIR, "results")

_G, _R, _Y, _B, _X, _O, _D = (
    "\033[92m", "\033[91m", "\033[93m", "\033[94m", "\033[0m", "\033[1m", "\033[90m")
ok = lambda s: f"{_G}{_O}{s}{_X}"
err = lambda s: f"{_R}{_O}{s}{_X}"
hdr = lambda s: f"{_O}{_B}{s}{_X}"


# --------------------------------------------------------------------------
# Generation
# --------------------------------------------------------------------------

def write_config(fmt, batches: int, per_batch: int, rel_tol: float, abs_tol: float,
                 model: str, timeout_cycles: int, seed: int) -> None:
    """Emit the include file the testbench pulls in."""
    path = os.path.join(TB_DIR, "gpnae_test_config.svh")
    with open(path, "w") as f:
        f.write("// Auto-generated by regression.py -- do not edit by hand.\n")
        f.write(f"// {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")
        f.write(f"  localparam int DATA_WIDTH       = {fmt.width};\n")
        f.write(f"  localparam int EXP_BITS         = {fmt.exp_bits};\n")
        f.write(f"  localparam int MAN_BITS         = {fmt.man_bits};\n")
        f.write(f'  localparam string FMT_NAME      = "{fmt.name}";\n')
        f.write(f"  localparam int NUM_BATCHES      = {batches};\n")
        f.write(f"  localparam int SIGNALS_PER_BATCH = {per_batch};\n")
        f.write(f"  localparam int SELU_TERMS       = {ACTIVATIONS['selu']['terms']};\n")
        f.write(f"  localparam int SIGMOID_TERMS    = {ACTIVATIONS['sigmoid']['terms']};\n")
        f.write(f"  localparam int TANH_TERMS       = {ACTIVATIONS['tanh']['terms']};\n")
        f.write(f"  localparam real REL_TOL         = {rel_tol};\n")
        f.write(f"  localparam real ABS_TOL         = {abs_tol};\n")
        f.write(f"  localparam int TIMEOUT_CYCLES   = {timeout_cycles};\n")
        f.write(f"  localparam int SEED             = {seed};\n")
        f.write(f'  localparam string REF_MODEL     = "{model}";\n')
        f.write('  localparam string STIM_DIR      = "testbenches/stimulus/";\n')


def generate_vectors(test_name: str, fmt, batches: int, per_batch: int, model: str,
                     seed: int, range_override: float = None) -> dict:
    """Write <act>_in.mem and <act>_exp.mem for all three activations."""
    os.makedirs(STIM_DIR, exist_ok=True)
    test = get_test(test_name)
    ranges = {}
    for act, cfg in ACTIVATIONS.items():
        rmax = range_override if range_override is not None else cfg["default_range"]
        stim = []
        for b in range(batches):
            rs = np.random.RandomState(seed + 1013 * b + 7919 * ACTIVATIONS[act]["code"])
            # Bound is swept, not random: batch b gets (b+1)/batches of rmax, so the last batch reaches full range.
            # Drawing it randomly let every batch fall short of large |x| and hid a known defect.
            # act_sweep and act_edge keep the full bound; act_edge places +/-rng literally, so it is the reproducer.
            if test["name"] in ("act_sweep", "act_edge"):
                rng = rmax
            else:
                frac = (b + 1) / batches
                rng = rmax * min(1.0, frac * rs.uniform(0.85, 1.15))
            stim.extend(test["gen_fn"](act, per_batch, rng, fmt, rs))
        gold = golden(stim, act, model, fmt)
        write_mem(os.path.join(STIM_DIR, f"{act}_in.mem"), stim, fmt)
        write_mem(os.path.join(STIM_DIR, f"{act}_exp.mem"), gold, fmt)
        ranges[act] = rmax
    return ranges


# --------------------------------------------------------------------------
# Run and parse
# --------------------------------------------------------------------------

def run_make() -> tuple:
    """Build and run via the project Makefile."""
    t0 = time.time()
    cmd = ["make", "verilator"]
    if os.environ.get("GPNAE_PIN", "0") == "1" and shutil.which("taskset"):
        cmd = ["taskset", "-c", "0"] + cmd
    r = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    return r.stdout + r.stderr, time.time() - t0


def parse_log(raw: str) -> dict:
    """Pull the per-activation RESULT/CYCLES lines and the overall verdict."""
    per_act = {}
    for m in re.finditer(
            r"RESULT (\w+) : total (\d+)\s+exact (\d+)\s+tol (\d+)\s+failed (\d+)\s+missing (\d+)",
            raw):
        act, tot, ex, tol, fail, miss = m.groups()
        per_act[act] = dict(total=int(tot), exact=int(ex), tol=int(tol),
                            failed=int(fail), missing=int(miss), cycles=0,
                            worst=0.0, mean=0.0)
    for m in re.finditer(r"CYCLES (\w+) :.*?per-input (\d+)", raw):
        act, cyc = m.groups()
        if act in per_act:
            per_act[act]["cycles"] = int(cyc)
    for m in re.finditer(r"ERRSTAT (\w+) : worst ([\d.]+)%\s+mean ([\d.]+)%", raw):
        act, worst, mean = m.groups()
        if act in per_act:
            per_act[act]["worst"] = float(worst)
            per_act[act]["mean"] = float(mean)

    passed = "RESULT: PASSED" in raw
    if not per_act and ("%Error" in raw or "Error" in raw):
        return dict(status="BUILD-ERROR", per_act={}, failed=1)
    total_failed = sum(a["failed"] + a["missing"] for a in per_act.values())
    return dict(status="PASS" if (passed and total_failed == 0) else "FAIL",
                per_act=per_act, failed=total_failed)


def print_activation(act: str, r: dict) -> None:
    tot = max(r["total"], 1)
    sym = ok("PASS") if (r["failed"] + r["missing"]) == 0 else err("FAIL")
    print(f"      {sym}  {act:<8} n {r['total']:5d}  exact {100*r['exact']/tot:5.1f}%  "
          f"tol {100*r['tol']/tot:5.1f}%  fail {r['failed']:4d}  miss {r['missing']:3d}  "
          f"err worst {r['worst']:7.4f}% mean {r['mean']:7.4f}%  {r['cycles']:4d} cyc/in")


# --------------------------------------------------------------------------
# Report
# --------------------------------------------------------------------------

def write_report(results, fmt, batches, per_batch, model, ranges, seed, abs_tol) -> str:
    """Plain-text report alongside the per-pattern logs."""
    os.makedirs(RESULTS_DIR, exist_ok=True)
    path = os.path.join(RESULTS_DIR, "gpnae_report.log")
    n_pass = sum(1 for r in results if r["status"] == "PASS")
    total_checks = sum(a["total"] for r in results for a in r["per_act"].values())
    total_fail = sum(a["failed"] + a["missing"] for r in results for a in r["per_act"].values())
    worst = max((a["worst"] for r in results for a in r["per_act"].values()), default=0.0)

    W = 100
    L = []
    L.append("=" * W)
    L.append("GPNAE — ACTIVATION REGRESSION REPORT")
    L.append("=" * W)
    L.append("")
    L.append(f"Date              : {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    L.append(f"Format            : {fmt.name}  {fmt.width} bits "
             f"(1 sign + {fmt.exp_bits} exp + {fmt.man_bits} mantissa), eps {fmt.eps:.3e}")
    L.append(f"Volume            : {batches} batches x {per_batch} signals = "
             f"{batches*per_batch} per activation")
    L.append(f"Element checks    : {total_checks}")
    L.append(f"Reference model   : {model}")
    L.append(f"Seed              : {seed}")
    L.append(f"Stimulus ranges   : " + ", ".join(f"{a} +/-{r}" for a, r in ranges.items()))
    L.append(f"Tolerance         : relative <= {suggested_rel_tol(fmt)*100:.4f}% "
             f"or absolute <= {abs_tol:g} (either bound passes)")
    L.append("")
    L.append(f"RESULT            : {'PASS' if n_pass == len(results) else 'FAIL'}  "
             f"({n_pass}/{len(results)} patterns, {total_fail} element failures)")
    L.append(f"Worst rel error   : {worst:.4f}%")
    L.append("")
    L.append("-" * W)
    L.append("PER-PATTERN RESULTS")
    L.append("-" * W)
    L.append(f"{'pattern':<18}{'activation':<11}{'n':>6}{'exact':>9}{'tol':>9}"
             f"{'failed':>8}{'missing':>9}{'worst err':>12}{'mean err':>12}")
    L.append("-" * W)
    for r in results:
        for act, a in r["per_act"].items():
            tot = max(a["total"], 1)
            L.append(f"{r['name']:<18}{act:<11}{a['total']:>6}"
                     f"{100*a['exact']/tot:>8.1f}%{100*a['tol']/tot:>8.1f}%"
                     f"{a['failed']:>8}{a['missing']:>9}"
                     f"{a['worst']:>11.4f}%{a['mean']:>11.4f}%")
        L.append("")
    L.append("-" * W)
    L.append("NOTES")
    L.append("-" * W)
    L.append("* The FP units truncate rather than round and the exponential is a finite")
    L.append("  Maclaurin series, so exact matches are the exception. Tolerance passes")
    L.append("  are the normal case and are not a defect.")
    L.append("* --model exact  compares against true mathematics, i.e. what a framework")
    L.append("                 such as TensorFlow produces. Use it to qualify the block.")
    L.append("* --model series compares against the finite series the MAC evaluates, with")
    L.append("                 every intermediate quantised and truncated as the hardware")
    L.append("                 does. Use it to separate an RTL fault from series")
    L.append("                 truncation or format precision.")
    L.append("* Stimulus ranges come from `python3 gpnae_tests.py --accuracy`, which shows")
    L.append("  where each term count stops tracking the true function for this format.")
    L.append("* `python3 number_formats.py --rtl` lists the RTL files that must be swapped")
    L.append("  or parameterised to retarget the block to another number format.")
    L.append("=" * W)
    with open(path, "w") as f:
        f.write("\n".join(L) + "\n")
    return path


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main() -> None:
    p = argparse.ArgumentParser(
        description="GPNAE activation regression",
        formatter_class=argparse.RawTextHelpFormatter)
    p.add_argument("--test", default=None, help="one stimulus pattern (default: all)")
    p.add_argument("--format", default="fp32", choices=sorted(FORMATS),
                   help="number format the RTL is built for")
    p.add_argument("--batches", type=int, default=8,
                   help="batches per activation; volume comes from this")
    p.add_argument("--per-batch", type=int, default=30,
                   help=f"signals per batch (<= {MAX_SIGNALS}, the FIFO depth)")
    p.add_argument("--range", type=float, default=None, help="override stimulus bound")
    p.add_argument("--model", default="exact", choices=["exact", "series"])
    p.add_argument("--rel-tol", type=float, default=None,
                   help="default scales with the format's precision")
    p.add_argument("--abs-tol", type=float, default=1e-6,
                   help="absolute bound, used in parallel with --rel-tol")
    p.add_argument("--timeout", type=int, default=200000)
    p.add_argument("--seed", type=int, default=1)
    p.add_argument("--write-coeffs", action="store_true",
                   help="also emit a coefficient ROM for --format")
    args = p.parse_args()

    if args.per_batch > MAX_SIGNALS:
        print(err(f"[ERROR] --per-batch must be <= {MAX_SIGNALS} (input FIFO depth)"))
        sys.exit(1)

    fmt = get_format(args.format)
    rel_tol = args.rel_tol if args.rel_tol is not None else suggested_rel_tol(fmt)
    tests = TESTS if args.test is None else [get_test(args.test)]
    per_act = args.batches * args.per_batch

    print(hdr(f"\n{'='*78}\n  GPNAE — Activation Regression Suite\n{'='*78}"))
    print(f"  Format      : {fmt.name}  ({fmt.width} bits: 1 + {fmt.exp_bits} exp + "
          f"{fmt.man_bits} man, eps {fmt.eps:.2e})")
    print(f"  Volume      : {args.batches} batches x {args.per_batch} = {per_act} per activation, "
          f"{per_act*3} per pattern")
    print(f"  Patterns    : {len(tests)}  ->  {len(tests)*per_act*3} element checks")
    print(f"  Reference   : {args.model}    seed {args.seed}")
    print(f"  Tolerance   : rel <= {rel_tol*100:.4f}%  abs <= {args.abs_tol}")
    print(hdr(f"{'='*78}"))

    if fmt.name != "fp32":
        print(f"  {_Y}NOTE{_X} the RTL must already be built for {fmt.name}; "
              f"see `python number_formats.py --rtl`")

    if args.write_coeffs:
        terms = max(c["terms"] for c in ACTIVATIONS.values())
        rom = os.path.join(ROOT, f"taylor_coeffs_{fmt.name}.mem")
        write_coeff_rom(rom, terms, fmt)
        print(f"  Coefficients: {rom}")

    write_config(fmt, args.batches, args.per_batch, rel_tol, args.abs_tol,
                 args.model, args.timeout, args.seed)

    results, ranges = [], {}
    for idx, t in enumerate(tests):
        print(f"\n  [{idx+1}/{len(tests)}] {_O}{t['name']}{_X}  —  {t['description']}")
        ranges = generate_vectors(t["name"], fmt, args.batches, args.per_batch,
                                  args.model, args.seed, args.range)
        raw, wall = run_make()

        os.makedirs(RESULTS_DIR, exist_ok=True)
        with open(os.path.join(RESULTS_DIR, f"{t['name']}.log"), "w") as f:
            f.write(raw)

        parsed = parse_log(raw)
        parsed["name"] = t["name"]
        parsed["wall"] = wall
        results.append(parsed)

        if parsed["status"] == "BUILD-ERROR":
            print(err("      BUILD ERROR — see the log"))
            for line in raw.splitlines():
                if "%Error" in line:
                    print(f"      {_D}{line.strip()}{_X}")
            sys.exit(1)

        for act, a in parsed["per_act"].items():
            print_activation(act, a)
        print(f"      {_D}{wall:.1f}s{_X}")

    n_pass = sum(1 for r in results if r["status"] == "PASS")
    total_checks = sum(a["total"] for r in results for a in r["per_act"].values())
    worst = max((a["worst"] for r in results for a in r["per_act"].values()), default=0.0)

    print(hdr(f"\n{'='*78}\n  SUMMARY\n{'='*78}"))
    for r in results:
        sym = ok("PASS") if r["status"] == "PASS" else err("FAIL")
        print(f"  {sym}  {r['name']}")
    print(f"\n  Element checks : {total_checks}")
    print(f"  Worst rel error: {worst:.4f}%   (tolerance {rel_tol*100:.4f}%)")
    verdict = ok("All patterns passed") if n_pass == len(results) else err(
        f"{len(results)-n_pass} pattern(s) failed")
    print(hdr(f"\n  Verdict : {verdict}"))
    print(f"  Report  : {write_report(results, fmt, args.batches, args.per_batch, args.model, ranges, args.seed, args.abs_tol)}")
    print(hdr(f"{'='*78}\n"))

    sys.exit(0 if n_pass == len(results) else 1)


if __name__ == "__main__":
    main()
