#!/usr/bin/env python3
"""GPNAE activation regression: generate stimulus and golden values, run the RTL under Verilator, score every element.

Writes testbenches/stimulus/<act>_{in,exp}.mem and testbenches/gpnae_test_config.svh, then runs `make verilator`.
Report lands in testbenches/results/gpnae_report.log. Use ./run_regression.sh, which sets the toolchain up first.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import time
from datetime import datetime

import numpy as np

from gpnae_tests import (ACTIVATIONS, MAX_SIGNALS, TESTS, get_test, golden,
                         write_coeff_rom, write_mem)
from number_formats import FORMATS, get_format, suggested_rel_tol

ROOT = os.path.dirname(os.path.abspath(__file__))
TB_DIR = os.path.join(ROOT, "testbenches")
STIM_DIR = os.path.join(TB_DIR, "stimulus")
RESULTS_DIR = os.path.join(TB_DIR, "results")

_G, _R, _Y, _B, _X, _O, _D = (
    "\033[92m", "\033[91m", "\033[93m", "\033[94m", "\033[0m", "\033[1m", "\033[90m")
ok = lambda s: f"{_G}{_O}{s}{_X}"
err = lambda s: f"{_R}{_O}{s}{_X}"
hdr = lambda s: f"{_O}{_B}{s}{_X}"


# --------------------------------------------------------------------------
# Generation
# --------------------------------------------------------------------------

def write_config(fmt, batches: int, per_batch: int, rel_tol: float, abs_tol: float,
                 model: str, timeout_cycles: int, seed: int, exact: bool = False,
                 coeff_file: str = "poly_coeffs.mem", req_rounding: str = None) -> None:
    """Emit the include file the testbench pulls in."""
    path = os.path.join(TB_DIR, "gpnae_test_config.svh")
    with open(path, "w") as f:
        # No timestamp: this file is tracked, and a timestamp would leave the tree dirty after every run.
        f.write("// Auto-generated by regression.py -- do not edit by hand.\n\n")
        f.write(f"  localparam int DATA_WIDTH       = {fmt.width};\n")
        f.write(f"  localparam int EXP_BITS         = {fmt.exp_bits};\n")
        f.write(f"  localparam int MAN_BITS         = {fmt.man_bits};\n")
        f.write(f'  localparam string FMT_NAME      = "{fmt.name}";\n')
        f.write(f"  localparam int NUM_BATCHES      = {batches};\n")
        f.write(f"  localparam int SIGNALS_PER_BATCH = {per_batch};\n")
        f.write(f"  localparam int SELU_TERMS       = {ACTIVATIONS['selu']['terms']};\n")
        f.write(f"  localparam int SIGMOID_TERMS    = {ACTIVATIONS['sigmoid']['terms']};\n")
        f.write(f"  localparam int TANH_TERMS       = {ACTIVATIONS['tanh']['terms']};\n")
        f.write(f"  localparam real REL_TOL         = {rel_tol};\n")
        f.write(f"  localparam real ABS_TOL         = {abs_tol};\n")
        f.write(f"  localparam int TIMEOUT_CYCLES   = {timeout_cycles};\n")
        f.write(f"  localparam int SEED             = {seed};\n")
        f.write(f'  localparam string REF_MODEL     = "{model}";\n')
        f.write('  localparam string STIM_DIR      = "testbenches/stimulus/";\n')
        f.write(f"  localparam bit EXACT_MATCH      = {1 if exact else 0};\n")
        f.write(f'  localparam string COEFF_FILE    = "{coeff_file}";\n')
        if req_rounding is None:
            import gpnae_model
            req_rounding = gpnae_model.REQ_ROUNDING  # the rounding the model's SELU requantize uses, from sienna_fmt_pkg
        f.write(f'  localparam string REQ_ROUNDING  = "{req_rounding}";\n')


def generate_vectors(test_name: str, fmt, batches: int, per_batch: int, model: str,
                     seed: int, range_override: float = None) -> dict:
    """Write <act>_in.mem and <act>_exp.mem for all three activations."""
    os.makedirs(STIM_DIR, exist_ok=True)
    test = get_test(test_name)
    ranges = {}
    for act, cfg in ACTIVATIONS.items():
        rmax = range_override if range_override is not None else cfg["default_range"]
        stim = []
        for b in range(batches):
            rs = np.random.RandomState(seed + 1013 * b + 7919 * ACTIVATIONS[act]["code"])
            # Bound is swept, not random: batch b gets (b+1)/batches of rmax, so the last batch reaches full range.
            # Drawing it randomly let every batch fall short of large |x| and hid a known defect.
            # act_sweep and act_edge keep the full bound; act_edge places +/-rng literally, so it is the reproducer.
            if test["name"] in ("act_sweep", "act_edge"):
                rng = rmax
            else:
                frac = (b + 1) / batches
                rng = rmax * min(1.0, frac * rs.uniform(0.85, 1.15))
            stim.extend(test["gen_fn"](act, per_batch, rng, fmt, rs))
        gold = golden(stim, act, model, fmt)
        write_mem(os.path.join(STIM_DIR, f"{act}_in.mem"), stim, fmt)
        write_mem(os.path.join(STIM_DIR, f"{act}_exp.mem"), gold, fmt)
        ranges[act] = rmax
    return ranges


# --------------------------------------------------------------------------
# Run and parse
# --------------------------------------------------------------------------

def run_make(lane: str = "gpnae") -> tuple:
    """Build and run via the project Makefile."""
    t0 = time.time()
    cmd = ["make", "verilator"]
    if lane == "poly":
        cmd += ["TESTBENCH=TB_gpnae_poly.sv", "TOP_MODULE=TB_gpnae_poly"]
    if os.environ.get("GPNAE_PIN", "0") == "1" and shutil.which("taskset"):
        cmd = ["taskset", "-c", "0"] + cmd
    r = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    return r.stdout + r.stderr, time.time() - t0


def parse_log(raw: str, expect_total: int = 0, expect_acts: int = 3) -> dict:
    """Pull the per-activation RESULT/CYCLES lines and the overall verdict."""
    per_act = {}
    for m in re.finditer(
            r"RESULT (\w+) : total (\d+)\s+exact (\d+)\s+tol (\d+)\s+failed (\d+)\s+missing (\d+)",
            raw):
        act, tot, ex, tol, fail, miss = m.groups()
        per_act[act] = dict(total=int(tot), exact=int(ex), tol=int(tol),
                            failed=int(fail), missing=int(miss), cycles=0,
                            worst=0.0, mean=0.0)
    for m in re.finditer(r"CYCLES (\w+) :.*?per-input (\d+)", raw):
        act, cyc = m.groups()
        if act in per_act:
            per_act[act]["cycles"] = int(cyc)
    for m in re.finditer(r"ERRSTAT (\w+) : worst ([\d.]+)%\s+mean ([\d.]+)%", raw):
        act, worst, mean = m.groups()
        if act in per_act:
            per_act[act]["worst"] = float(worst)
            per_act[act]["mean"] = float(mean)

    passed = "RESULT: PASSED" in raw
    if not per_act and ("%Error" in raw or "Error" in raw):
        return dict(status="BUILD-ERROR", per_act={}, failed=1)
    total_failed = sum(a["failed"] + a["missing"] for a in per_act.values())

    # "Zero failures" only means something once the expected checks actually ran. A build that
    # does not launch, or a testbench that silently checks a handful of elements, otherwise
    # reads as a clean pass -- which has happened more than once in this repo.
    short = []
    if len(per_act) != expect_acts:
        short.append(f"{len(per_act)} of {expect_acts} activations reported")
    if expect_total:
        for act, a in sorted(per_act.items()):
            if a["total"] != expect_total:
                short.append(f"{act} checked {a['total']} of {expect_total}")

    if short:
        return dict(status="NO-RESULTS", per_act=per_act, failed=max(1, total_failed),
                    short=short)
    return dict(status="PASS" if (passed and total_failed == 0) else "FAIL",
                per_act=per_act, failed=total_failed, short=[])


def print_activation(act: str, r: dict) -> None:
    tot = max(r["total"], 1)
    sym = ok("PASS") if (r["failed"] + r["missing"]) == 0 else err("FAIL")
    print(f"      {sym}  {act:<8} n {r['total']:5d}  exact {100*r['exact']/tot:5.1f}%  "
          f"tol {100*r['tol']/tot:5.1f}%  fail {r['failed']:4d}  miss {r['missing']:3d}  "
          f"err worst {r['worst']:7.4f}% mean {r['mean']:7.4f}%  {r['cycles']:4d} cyc/in")


# --------------------------------------------------------------------------
# Report
# --------------------------------------------------------------------------

def write_report(results, fmt, batches, per_batch, model, ranges, seed, abs_tol) -> str:
    """Plain-text report alongside the per-pattern logs."""
    os.makedirs(RESULTS_DIR, exist_ok=True)
    path = os.path.join(RESULTS_DIR, "gpnae_report.log")
    n_pass = sum(1 for r in results if r["status"] == "PASS")
    total_checks = sum(a["total"] for r in results for a in r["per_act"].values())
    total_fail = sum(a["failed"] + a["missing"] for r in results for a in r["per_act"].values())
    worst = max((a["worst"] for r in results for a in r["per_act"].values()), default=0.0)

    W = 100
    L = []
    L.append("=" * W)
    L.append("GPNAE — ACTIVATION REGRESSION REPORT")
    L.append("=" * W)
    L.append("")
    L.append(f"Date              : {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    L.append(f"Format            : {fmt.name}  {fmt.width} bits "
             f"(1 sign + {fmt.exp_bits} exp + {fmt.man_bits} mantissa), eps {fmt.eps:.3e}")
    L.append(f"Volume            : {batches} batches x {per_batch} signals = "
             f"{batches*per_batch} per activation")
    L.append(f"Element checks    : {total_checks}")
    L.append(f"Reference model   : {model}")
    L.append(f"Seed              : {seed}")
    L.append(f"Stimulus ranges   : " + ", ".join(f"{a} +/-{r}" for a, r in ranges.items()))
    L.append(f"Tolerance         : relative <= {suggested_rel_tol(fmt)*100:.4f}% "
             f"or absolute <= {abs_tol:g} (either bound passes)")
    L.append("")
    L.append(f"RESULT            : {'PASS' if n_pass == len(results) else 'FAIL'}  "
             f"({n_pass}/{len(results)} patterns, {total_fail} element failures)")
    L.append(f"Worst rel error   : {worst:.4f}%")
    L.append("")
    L.append("-" * W)
    L.append("PER-PATTERN RESULTS")
    L.append("-" * W)
    L.append(f"{'pattern':<18}{'activation':<11}{'n':>6}{'exact':>9}{'tol':>9}"
             f"{'failed':>8}{'missing':>9}{'worst err':>12}{'mean err':>12}")
    L.append("-" * W)
    for r in results:
        for act, a in r["per_act"].items():
            tot = max(a["total"], 1)
            L.append(f"{r['name']:<18}{act:<11}{a['total']:>6}"
                     f"{100*a['exact']/tot:>8.1f}%{100*a['tol']/tot:>8.1f}%"
                     f"{a['failed']:>8}{a['missing']:>9}"
                     f"{a['worst']:>11.4f}%{a['mean']:>11.4f}%")
        L.append("")
    L.append("-" * W)
    L.append("NOTES")
    L.append("-" * W)
    L.append("* The FP units truncate rather than round and the activation is a finite")
    L.append("  polynomial, so exact matches are the exception. Tolerance passes are the")
    L.append("  normal case and are not a defect.")
    L.append("* Two lanes exist and they are NOT numerically equivalent:")
    L.append("    gpnae       evaluates e^x by Maclaurin series, then reshapes it")
    L.append("                (divider for sigmoid and tanh). terms_i trades accuracy")
    L.append("                against speed. Qualify with --model series or --model exact.")
    L.append("    gpnae_poly  fits each activation directly, so there is no exponential")
    L.append("                and no divider. terms_i is inert: truncating a fitted")
    L.append("                polynomial is meaningless. Qualify with --model exact ONLY;")
    L.append("                --model series describes a route this lane does not take.")
    L.append("* --model exact  compares against true mathematics, i.e. what a framework")
    L.append("                 such as TensorFlow produces. Use it to qualify either lane.")
    L.append("* --model series compares against the finite series the MAC evaluates, with")
    L.append("                 every intermediate quantised and truncated as the hardware")
    L.append("                 does. Use it on the gpnae lane to separate an RTL fault")
    L.append("                 from series truncation or format precision.")
    L.append("* Stimulus ranges come from `python3 gpnae_tests.py --accuracy`, which shows")
    L.append("  where each term count stops tracking the true function for this format.")
    L.append("* `python3 number_formats.py --rtl` lists the RTL files that must be swapped")
    L.append("  or parameterised to retarget the block to another number format.")
    L.append("=" * W)
    with open(path, "w") as f:
        f.write("\n".join(L) + "\n")
    return path


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

INT8_ACTS = (("selu", 1), ("sigmoid", 2), ("tanh", 3), ("relu", 4), ("linear", 5))  # TB_gpnae_poly's order in int8
N_RAND_INT8, N_SAT_INT8 = 32, 8  # random lane parameter sets per activation, and how many saturate the rescale; bit-exact only
STREAM_POLY = ((0, 20), (0, 17), (0, 1), (0, 16), (2, 16), (2, 16), (2, 5), (1, 16), (1, 5), (1, 1), (1, 32), (0, 32), (1, 2),
               (0, 16), (2, 1))  # (mode, elements): 0 write then last_i, 1 last_i with the last write, 2 write while busy
STREAM_BYP = ((0, 20), (0, 17), (0, 1), (0, 16), (2, 8), (1, 16), (1, 5), (1, 1), (1, 32), (0, 32), (1, 2), (0, 16),
              (2, 1))  # ReLU and linear emit 16 cycles after capture, so a busy group is at most 8
S_IDLE, S_NEXT, LANE_K = 0, 8, 16  # gpnae_poly_int8's G_IDLE and G_NEXT encodings, and its group size


def rand_params_int8(rng, code, sat):
    """A random lane parameter set; sat makes mx / 2^shx >= 256, so inputs with |q - z_in| >= 128 saturate Q4.11."""
    import gpnae_model as gm
    mx = int(rng.integers(1 << 14, 1 << 15)) if sat else int(rng.integers(0, 1 << 15))
    shx = int(rng.integers(0, 7)) if sat else int(rng.integers(8, 21))  # shx >= 8 keeps 255 * mx / 2^shx below 2^15
    zin = int(rng.integers(-128, 128))
    if code == 1:
        return gm.Int8Params(mx, shx, zin, int(rng.integers(1 << 30, 1 << 31)), int(rng.integers(-31, 6)),
                             int(rng.integers(-128, 128)))
    return gm.Int8Params(mx, shx, zin, 0, 0, 0)


def rescale_saturates(p) -> bool:
    """Whether some int8 input's rescale leaves Q4.11 before the clip."""
    q = np.arange(-128, 128, dtype=np.int64)
    raw = (q - p.zin) * p.mx
    raw = raw if p.shx == 0 else (raw + (1 << (p.shx - 1))) >> p.shx
    return bool(((raw > 32767) | (raw < -32768)).any())


def stream_starts(mode, n):
    """The group starts one stream group should produce, as (state it starts from, size)."""
    if mode == 2:
        first, via = min(LANE_K, n), S_NEXT  # queued while the lane works: G_NEXT takes it
    elif mode == 1:
        first, via = max(1, min(LANE_K, n - 1)), S_IDLE  # G_IDLE counts the FIFO before the last write; a lone one waits
    else:
        first, via = min(LANE_K, n), S_IDLE
    out, left = [(via, first)], n - first
    while left:
        out.append((S_NEXT, min(LANE_K, left)))  # the rest is already queued: G_NEXT takes it, 16 at a time
        left -= out[-1][1]
    return out


def write_stream_int8(lane, rng) -> dict:
    """stream_*.mem for TB_gpnae_poly's protocol edges: every control word, a gated case and a saturating random set each."""
    import gpnae_model as gm
    segs = []
    for act, code in INT8_ACTS:
        segs.append((code, gm.int8_params(gm.INT8_CASES[act][0], code)))
        if code <= 3:
            segs.append((code, rand_params_int8(rng, code, True)))
    segs += [(cw, gm.int8_params(gm.INT8_CASES["tanh"][1], 3)) for cw in (0, 6, 7)]  # every other control word runs tanh
    seg_l, grp_l, bnd, q_all, y_all = [], [], [], [], []
    for cw, p in segs:
        script = STREAM_BYP if cw in (4, 5) else STREAM_POLY
        n_el = sum(n for _, n in script)
        q = np.concatenate([rng.permutation(256) for _ in range(-(-n_el // 256))]).astype(np.int64)[:n_el] - 128
        q_all += [int(v) for v in q]
        y_all += [int(v) for v in lane.run(q, cw, p)]
        seg_l.append(f"{cw:02x}{len(script):02x}{p.mx:04x}{p.shx:02x}{p.zin & 0xFF:02x}{p.mout:08x}{p.shout & 0xFF:02x}"
                     f"{p.zout & 0xFF:02x}\n")
        for mode, n in script:
            grp_l.append(f"{mode:02x}{n:02x}{len(bnd):04x}\n")
            bnd += stream_starts(mode, n)
    files = {"stream_seg.mem": seg_l, "stream_grp.mem": grp_l,
             "stream_in.mem": [f"{v & 0xFF:02x}\n" for v in q_all], "stream_exp.mem": [f"{v & 0xFF:02x}\n" for v in y_all],
             "stream_bnd.mem": [f"{v:02x}{s:02x}\n" for v, s in bnd],
             "stream_cnt.mem": [f"{v:08x}\n" for v in (len(seg_l), len(grp_l), len(q_all), len(bnd))]}
    for name, lines in files.items():
        with open(os.path.join(STIM_DIR, name), "w") as fh:
            fh.write("".join(lines))
    return {"segments": len(seg_l), "groups": len(grp_l), "elements": len(q_all), "starts": len(bnd)}


def run_int8(args) -> int:
    """int8 lane: every int8 input at each gpnae_model.INT8_CASES case, bit-exact against the lane model, then accuracy."""
    import json
    import types

    import gpnae_model as gm
    if args.lane != "poly":
        print(err("[ERROR] the int8 lane is gpnae_poly; use --lane poly"))
        return 1
    per = MAX_SIGNALS
    n_cases = len(gm.INT8_CASES["tanh"])
    assert all(len(gm.INT8_CASES[a]) == n_cases for a, _ in INT8_ACTS), "every activation needs the same number of cases"
    case_batches = n_cases * 256 // per
    batches = (n_cases + N_RAND_INT8) * 256 // per  # the cases first, then the random sets
    fmt = types.SimpleNamespace(name="int8", width=8, exp_bits=0, man_bits=7)
    coeff = gm.coeff_file(gm.INT8)
    lane = gm.Lane(gm.INT8, gm.read_rom(os.path.join(ROOT, coeff)))
    write_config(fmt, batches, per, 0.0, 0.0, "hw", args.timeout, args.seed, True, coeff)
    rs = np.random.RandomState(args.seed)
    rr = np.random.default_rng([args.seed, 12])  # the random parameter sets and their input order
    os.makedirs(STIM_DIR, exist_ok=True)
    rows, rand_sets = [], {}
    for act, code in INT8_ACTS:
        stim, gold, par = [], [], []
        for case in gm.INT8_CASES[act]:
            p = gm.int8_params(case, code)
            q = rs.permutation(256).astype(np.int64) - 128  # every int8 input once, in a seeded order
            y = lane.run(q, code, p)
            stim += [int(v) for v in q]
            gold += [int(v) for v in y]
            par += [p] * (256 // per)
            if code <= 3:
                rows.append((act, case, p, gm.accuracy_int8(y, q, code, case)))
        rand_sets[act] = [rand_params_int8(rr, code, k < N_SAT_INT8) for k in range(N_RAND_INT8)]
        for p in rand_sets[act]:
            q = rr.permutation(256).astype(np.int64) - 128
            stim += [int(v) for v in q]
            gold += [int(v) for v in lane.run(q, code, p)]
            par += [p] * (256 // per)
        with open(os.path.join(STIM_DIR, f"{act}_in.mem"), "w") as fh:
            fh.write("".join(f"{v & 0xFF:02x}\n" for v in stim))
        with open(os.path.join(STIM_DIR, f"{act}_exp.mem"), "w") as fh:
            fh.write("".join(f"{v & 0xFF:02x}\n" for v in gold))
        with open(os.path.join(STIM_DIR, f"{act}_par.mem"), "w") as fh:
            fh.write("".join(f"{p.mx:04x}{p.shx:02x}{p.zin & 0xFF:02x}{p.mout:08x}{p.shout & 0xFF:02x}{p.zout & 0xFF:02x}\n"
                             for p in par))
    n_sat = {act: sum(rescale_saturates(p) for p in s) for act, s in rand_sets.items()}
    stream = write_stream_int8(lane, np.random.default_rng([args.seed, 13]))
    print(hdr(f"\n{'='*78}\n  GPNAE int8 lane: {n_cases} cases and {N_RAND_INT8} random sets x 256 inputs per activation, "
              f"a {stream['elements']}-element protocol stream, seed {args.seed}\n{'='*78}"))
    raw, wall = run_make("poly")
    os.makedirs(RESULTS_DIR, exist_ok=True)
    with open(os.path.join(RESULTS_DIR, "int8_exhaustive.log"), "w") as fh:
        fh.write(raw)
    parsed = parse_log(raw, expect_total=batches * per, expect_acts=len(INT8_ACTS))
    for act, a in parsed["per_act"].items():
        print_activation(act, a)
    bad = {act: [0, 0] for act, _ in INT8_ACTS}  # wrong or missing outputs: cases, random sets
    for m in re.finditer(r"BATCHFAIL (\w+) b(\d+) : (\d+)", raw):
        if m.group(1) in bad:
            bad[m.group(1)][int(m.group(2)) >= case_batches] += int(m.group(3))
    se = re.search(r"STREAM : elements (\d+)\s+exact (\d+)\s+failed (\d+)\s+missing (\d+)\s+extra (\d+)", raw)
    sb = re.search(r"STREAM boundaries : expected (\d+)\s+observed (\d+)\s+wrong (\d+)\s+edge errors (\d+)", raw)
    stream_ok = bool(se and sb) and int(se.group(1)) == stream["elements"] and int(se.group(2)) == stream["elements"] \
        and int(se.group(5)) == 0 and int(sb.group(1)) == stream["starts"] and int(sb.group(2)) == stream["starts"] \
        and int(sb.group(3)) == 0 and int(sb.group(4)) == 0
    exact_ok = parsed["status"] == "PASS" and stream_ok
    tot = {act: gm.merge_acc(a for x, c, _, a in rows if x == act and c.gated) for act, _ in INT8_ACTS[:3]}
    tol = f"rel <= {100 * gm.REL_TOL_INT8:.2f}% or abs <= {gm.ABS_TOL_LSB} LSB"
    n_c, n_r = n_cases * 256, N_RAND_INT8 * 256
    ran = lambda a: a in parsed["per_act"] and parsed["per_act"][a]["total"] == batches * per  # the TB checked all of it
    part = lambda a, k, n: f"{a} {n - bad[a][k]}/{n}" if ran(a) else f"{a} no result"
    L = [f"GPNAE int8 lane, seed {args.seed}: bit-exact against gpnae_model, then the lane against exact_int8 with GPNAE's tolerance",
         f"BITEXACT: {'PASS' if exact_ok else (parsed['status'] if parsed['status'] != 'PASS' else 'FAIL')}  "
         + "  ".join(f"{a} {v['exact']}/{v['total']}" for a, v in parsed["per_act"].items())
         + (f"  stream {se.group(2)}/{se.group(1)}" if se else "  stream NO-RESULT"),
         "  INT8_CASES, every int8 input: " + "  ".join(part(a, 0, n_c) for a, _ in INT8_ACTS),
         f"  random sets ({N_RAND_INT8} per activation, bit-exact only): "
         + "  ".join(f"{part(a, 1, n_r)} ({n_sat[a]} saturate the rescale)" for a, _ in INT8_ACTS),
         f"  protocol stream ({stream['segments']} segments, {stream['groups']} groups, no reset between groups): "
         + (f"exact {se.group(2)}/{se.group(1)}, failed {se.group(3)}, missing {se.group(4)}, extra {se.group(5)}; group starts "
            f"{sb.group(2)} observed of {sb.group(1)} expected, {sb.group(3)} wrong, {sb.group(4)} edge errors"
            if se and sb else "NO RESULT (the TB did not report the stream)"),
         f"{'act':<8}{'s_in':>10}{'z_in':>6}{'mx':>7}{'shx':>4}{'s_out':>10}{'z_out':>6}{'mout':>12}{'shout':>6}"
         f"{'fail':>6}{'rel %':>8}{'LSB':>5}{'real':>7}{'differ':>7}{'gated':>6}"]
    for act, case, p, a in rows:
        L.append(f"{act:<8}{case.s_in:>10.6f}{case.z_in:>6}{p.mx:>7}{p.shx:>4}{case.s_out:>10.6f}{case.z_out:>6}"
                 f"{p.mout:>12}{p.shout:>6}{a.fail:>6}{100 * a.worst_rel:>8.2f}{a.worst_lsb:>5}{a.real_lsb:>7.2f}"
                 f"{a.differ:>7}{'yes' if case.gated else 'no':>6}")
    for act, a in tot.items():
        L.append(f"{act:<8} {'within' if a.ok else 'OUTSIDE'} tolerance ({tol}): {a.fail} gated outputs outside, worst "
                 f"{100 * a.worst_rel:.2f}% where |d| > 1 LSB, worst {a.worst_lsb} LSB, {a.real_lsb:.2f} LSB against the "
                 f"unquantized function")
    missed = [act for act, a in tot.items() if not a.ok]
    L.append(f"ACCURACY: {'PASS' if not missed else 'MISSED'} ({tol} on every gated output"
             + (f"; outside: {', '.join(missed)}, an open accuracy item" if missed else "") + "; reported, not gated)")
    k_rand = len(L)
    L.append("random sets (mx shx z_in mout shout z_out), in stimulus order after the cases:")
    for act, s in rand_sets.items():
        L.append(f"  {act}: " + " ".join(f"({p.mx} {p.shx} {p.zin} {p.mout} {p.shout} {p.zout})" for p in s))
    with open(os.path.join(RESULTS_DIR, "gpnae_int8_report.log"), "w") as fh:
        fh.write("\n".join(L) + "\n")
    fields = lambda a: {"pass": a.ok, "fail": a.fail, "worst_rel": a.worst_rel, "worst_lsb": a.worst_lsb,
                        "real_lsb": a.real_lsb, "differ": a.differ}
    summary = {act: {"rel_tol": gm.REL_TOL_INT8, "abs_tol_lsb": gm.ABS_TOL_LSB, **fields(a), "cases": []}
               for act, a in tot.items()}  # per activation: the tolerance, the gated cases merged, and every case
    for act, case, p, a in rows:
        summary[act]["cases"].append({"s_in": float(case.s_in), "z_in": int(case.z_in), "s_out": float(case.s_out),
                                      "z_out": int(case.z_out), "gated": bool(case.gated), **fields(a)})
    with open(os.path.join(RESULTS_DIR, "gpnae_int8_accuracy.json"), "w") as fh:
        json.dump({"seed": args.seed, "bitexact": exact_ok, "activations": summary}, fh, indent=1)
    print("\n".join(L[1:k_rand]))
    print(f"  {_D}{wall:.1f}s{_X}")
    return 0 if exact_ok else 1


def main() -> None:
    p = argparse.ArgumentParser(
        description="GPNAE activation regression",
        formatter_class=argparse.RawTextHelpFormatter)
    p.add_argument("--test", default=None, help="one stimulus pattern (default: all)")
    p.add_argument("--format", default="fp32", choices=sorted(FORMATS) + ["int8"],
                   help="number format the RTL is built for")
    p.add_argument("--batches", type=int, default=8,
                   help="batches per activation; volume comes from this")
    p.add_argument("--per-batch", type=int, default=30,
                   help=f"signals per batch (<= {MAX_SIGNALS}, the FIFO depth)")
    p.add_argument("--range", type=float, default=None, help="override stimulus bound")
    p.add_argument("--model", default="exact", choices=["exact", "series", "hw"])
    p.add_argument("--rel-tol", type=float, default=None,
                   help="default scales with the format's precision")
    p.add_argument("--abs-tol", type=float, default=1e-6,
                   help="absolute bound, used in parallel with --rel-tol")
    p.add_argument("--timeout", type=int, default=200000)
    p.add_argument("--seed", type=int, default=1)
    p.add_argument("--lane", default="gpnae", choices=["gpnae", "poly"],
                   help="gpnae: the published Taylor lane; poly: the lane sienna_top uses")
    p.add_argument("--write-coeffs", action="store_true",
                   help="also emit a coefficient ROM for --format")
    args = p.parse_args()

    if args.per_batch > MAX_SIGNALS:
        print(err(f"[ERROR] --per-batch must be <= {MAX_SIGNALS} (input FIFO depth)"))
        sys.exit(1)
    if args.format == "int8":
        sys.exit(run_int8(args))

    fmt = get_format(args.format)
    rel_tol = args.rel_tol if args.rel_tol is not None else suggested_rel_tol(fmt)
    exact = args.model == "hw"  # bit-exact model of gpnae_poly: every output must match bit for bit
    if exact:
        if args.lane != "poly":
            print(err("[ERROR] --model hw models gpnae_poly only; use --lane poly"))
            sys.exit(1)
        rel_tol, args.abs_tol = 0.0, 0.0
    coeff = "poly_coeffs.mem" if fmt.name == "fp32" else f"poly_coeffs_{fmt.name}.mem"
    tests = TESTS if args.test is None else [get_test(args.test)]
    per_act = args.batches * args.per_batch

    print(hdr(f"\n{'='*78}\n  GPNAE — Activation Regression Suite\n{'='*78}"))
    print(f"  Format      : {fmt.name}  ({fmt.width} bits: 1 + {fmt.exp_bits} exp + "
          f"{fmt.man_bits} man, eps {fmt.eps:.2e})")
    print(f"  Volume      : {args.batches} batches x {args.per_batch} = {per_act} per activation, "
          f"{per_act*3} per pattern")
    print(f"  Patterns    : {len(tests)}  ->  {len(tests)*per_act*3} element checks")
    print(f"  Reference   : {args.model}    seed {args.seed}    lane {args.lane}")
    print(f"  Tolerance   : rel <= {rel_tol*100:.4f}%  abs <= {args.abs_tol}")
    print(hdr(f"{'='*78}"))

    if fmt.name != "fp32":
        print(f"  {_Y}NOTE{_X} the RTL must already be built for {fmt.name}; "
              f"see `python number_formats.py --rtl`")

    if args.write_coeffs:
        terms = max(c["terms"] for c in ACTIVATIONS.values())
        rom = os.path.join(ROOT, f"taylor_coeffs_{fmt.name}.mem")
        write_coeff_rom(rom, terms, fmt)
        print(f"  Coefficients: {rom}")

    write_config(fmt, args.batches, args.per_batch, rel_tol, args.abs_tol,
                 args.model, args.timeout, args.seed, exact, coeff)

    results, ranges = [], {}
    for idx, t in enumerate(tests):
        print(f"\n  [{idx+1}/{len(tests)}] {_O}{t['name']}{_X}  —  {t['description']}")
        ranges = generate_vectors(t["name"], fmt, args.batches, args.per_batch,
                                  args.model, args.seed, args.range)
        raw, wall = run_make(args.lane)

        os.makedirs(RESULTS_DIR, exist_ok=True)
        with open(os.path.join(RESULTS_DIR, f"{t['name']}.log"), "w") as f:
            f.write(raw)

        parsed = parse_log(raw, expect_total=args.batches * args.per_batch)
        parsed["name"] = t["name"]
        parsed["wall"] = wall
        results.append(parsed)

        if parsed["status"] == "BUILD-ERROR":
            print(err("      BUILD ERROR — see the log"))
            for line in raw.splitlines():
                if "%Error" in line:
                    print(f"      {_D}{line.strip()}{_X}")
            sys.exit(1)

        if parsed["status"] == "NO-RESULTS":
            print(err("      NO RESULTS — the run did not check what it should have"))
            for line in parsed["short"]:
                print(f"      {_D}{line}{_X}")
            print(err("      Treating as failure. Check the simulator actually ran."))
            sys.exit(1)

        for act, a in parsed["per_act"].items():
            print_activation(act, a)
        print(f"      {_D}{wall:.1f}s{_X}")

    n_pass = sum(1 for r in results if r["status"] == "PASS")
    total_checks = sum(a["total"] for r in results for a in r["per_act"].values())
    worst = max((a["worst"] for r in results for a in r["per_act"].values()), default=0.0)

    print(hdr(f"\n{'='*78}\n  SUMMARY\n{'='*78}"))
    for r in results:
        sym = ok("PASS") if r["status"] == "PASS" else err("FAIL")
        print(f"  {sym}  {r['name']}")
    print(f"\n  Element checks : {total_checks}")
    print(f"  Worst rel error: {worst:.4f}%   (tolerance {rel_tol*100:.4f}%)")
    verdict = ok("All patterns passed") if n_pass == len(results) else err(
        f"{len(results)-n_pass} pattern(s) failed")
    print(hdr(f"\n  Verdict : {verdict}"))
    print(f"  Report  : {write_report(results, fmt, args.batches, args.per_batch, args.model, ranges, args.seed, args.abs_tol)}")
    print(hdr(f"{'='*78}\n"))

    sys.exit(0 if n_pass == len(results) else 1)


if __name__ == "__main__":
    main()
